---
title: "Abbildungen Modell Ergebnisse"
author: ""
date: ""
output: html_document
---

```{r Setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# Directory um Abbildungen zu speichern
savePath <- paste("figures/", gsub(":", "-", gsub(" ", "_", Sys.time())), sep="")
dir.create(savePath)
```

```{r packages, echo=FALSE, eval = TRUE,  message= FALSE}
# packages
require(tidyverse)
require(seewave)
require(scales)
require(reshape2)
```

```{r function declaratoins, echo=FALSE, eval = TRUE,  message= FALSE}
plotPhase <- function(dataModel, variable, colorScale, fontSettings, legendTitle, xlabel) {
  ggPhase <- ggplot(data = dataModel, aes(x=frequency, y=mad/3.1451*180)) +
              geom_line(aes(group = factor(variable), color=factor(variable))) +
              scale_x_settings +
              xlab(xlabel) + ylab("Phasenverschiebung [°]") +
              colorScale + fontSettings + guides(col=guide_legend(legendTitle))
  ggPhase
}

plotEnergy <- function(dataModel, variable, colorScale, fontSettings, legendTitle, xlabel) {
  ggPhase <- ggplot(data = dataModel, aes(x=frequency, y=20*log10(energy))) +
              geom_line(aes(group = factor(variable), color=factor(variable))) +
              scale_x_settings +
              xlab(xlabel) + ylab("Verstärkung [dB]") +
              colorScale + fontSettings + guides(col=guide_legend(legendTitle))
  ggPhase
}

plotStandEnergy <- function(dataModel, variable, colorScale, fontSettings, legendTitle, xlabel) {
  for(iter in unique(variable)){
    dataModel$normEnergy[variable == iter] <- dataModel$energy[variable == iter] / dataModel$energy[variable == iter & dataModel$frequency == min(dataModel$frequency)]
  }
  
  ggPhase <- ggplot(data = dataModel, aes(x=frequency, y=20*log10(normEnergy))) +
              geom_line(aes(group = factor(variable), color=factor(variable))) +
              scale_x_settings +
              xlab(xlabel) + ylab("Verstärkung [dB]") +
              colorScale + fontSettings + guides(col=guide_legend(legendTitle))
  ggPhase
}

savePlot <- function(g, plotName, w, h){
  ggsave(paste(savePath, "/", plotName, ".eps", sep =""), g, device = "eps", width  = w, height = h)
  ggsave(paste(savePath, "/", plotName, ".png", sep =""), g, device = "png", width = w, height = h, dpi = 600)
}
```


## Bodeplots
```{r Plot Ekemente, echo=FALSE, eval = TRUE,  message= FALSE}
colorScale6 <- scale_color_manual(values=c('#000033','#000066','#000099','#0000CC','#0000FF','#3366CC'))
colorScale7 <- scale_color_manual(values=c('#000033','#000066','#000099','#0000CC','#0000FF','#3366CC','#6699CC')) 
colorScale2 <- scale_color_manual(values=c('#000033','#6699CC')) 
colorScale4 <- scale_color_manual(values=c('black','blue','green','red')) 



fontSettings <- theme(legend.text = element_text(size=12), legend.box = "horizontal",
                      plot.title = element_text(size=13, face="bold", hjust=0.5, lineheight=1.2),
                      plot.subtitle = element_text(size=10, face="italic", hjust=0.5),
                      axis.title.x = element_text(size=12), 
                      axis.title.y = element_text(size=12),  
                      axis.text.x = element_text(size=12),  
                      axis.text.y = element_text(size=12))

scale_x_settings <- scale_x_continuous(trans = log10_trans(), 
                                       breaks = trans_breaks("log10", function(x) 10^x),
                                       labels = trans_format("log10", math_format(10^.x))) 
```


### mRNA Degradationsrate d0
```{r Abbildungen d0, echo=FALSE, eval = TRUE,  message= FALSE}
dataModel <- read.table("modelAnalysis/result_d.txt",header=T) %>% arrange(frequency) 
ggPhase.d0 <- plotPhase(dataModel, dataModel$d0, colorScale6, fontSettings, expression("Degradationsrate d"[0]*":"), "Frequenz [AU]")
ggEnergy.d0 <- plotEnergy(dataModel, dataModel$d0, colorScale6, fontSettings,expression("Degradationsrate d"[0]*":"), "Frequenz [AU]")
ggStandEnergy.d0 <- plotStandEnergy(dataModel, dataModel$d0, colorScale6, fontSettings, expression("Degradationsrate d"[0]*":"), "Frequenz [AU]")

gg.d0 <- ggarrange(ggEnergy.d0, ggStandEnergy.d0, ggPhase.d0, 
                   nrow = 3, ncol = 1, common.legend = TRUE, legend = "bottom")
gg.d0
savePlot(gg.d0, "bodeplot_d0", w = 8, h = 9)

```


### mRNA Translationsrate k1
```{r Abbildungen k1, echo=FALSE, eval = TRUE,  message= FALSE}
dataModel <- read.table("modelAnalysis/result_k.txt",header=T) %>% arrange(frequency) 
ggPhase.k1 <- plotPhase(dataModel, dataModel$k1, colorScale6, fontSettings, expression("Translationsrate k"[1]*":"), "Frequenz [AU]")
ggEnergy.k1 <- plotEnergy(dataModel, dataModel$k1, colorScale6, fontSettings, expression("Translationsrate k"[1]*":"), "Frequenz [AU]")
ggStandEnergy.k1 <- plotStandEnergy(dataModel, dataModel$k1, colorScale6, fontSettings, expression("Translationsrate k"[1]*":"), "Frequenz [AU]")

gg.k1 <- ggarrange(ggEnergy.k1, ggStandEnergy.k1, ggPhase.k1, 
                   nrow = 3, ncol = 1, common.legend = TRUE, legend = "bottom")
gg.k1
savePlot(gg.k1, "bodeplot_k1", w = 8, h = 9)
```


### Offset
```{r Abbildungen Offset, echo=FALSE, eval = TRUE,  message= FALSE}
dataModel <- read.table("modelAnalysis/result_offset.txt",header=T) %>% arrange(frequency) %>% dplyr::filter(frequency >= 0.001)

ggPhase.offset <- plotPhase(dataModel, dataModel$off, colorScale7, fontSettings, "offset:", "Frequenz [AU]")
ggEnergy.offset <- plotEnergy(dataModel, dataModel$off, colorScale7, fontSettings, "offset:", "Frequenz [AU]")
ggStandEnergy.offset <- plotStandEnergy(dataModel, dataModel$off, colorScale7, fontSettings, "offset:", "Frequenz [AU]")

gg.offset <- ggarrange(ggEnergy.offset, ggStandEnergy.offset, ggPhase.offset, 
                   nrow = 3, ncol = 1, common.legend = TRUE, legend = "bottom")
gg.offset
savePlot(gg.offset, "bodeplot_offset", w = 8, h = 9)

```


### Basale Transkriptionsrate
```{r Anbildungen Basale Transkriptionsrate, echo=FALSE, eval = TRUE,  message= FALSE}
dataModel <- read.table("modelAnalysis/result_basalLevel.txt",header=T) %>% arrange(frequency) 
ggPhase.basal <- plotPhase(dataModel, dataModel$basal, colorScale7, fontSettings, "basal level:", "Frequenz [AU]")
ggEnergy.basal <- plotEnergy(dataModel, dataModel$basal, colorScale7, fontSettings, "basal level:", "Frequenz [AU]")
ggStandEnergy.basal <- plotStandEnergy(dataModel, dataModel$basal, colorScale7, fontSettings, "basal level:", "Frequenz [AU]")

gg.basal <- ggarrange(ggEnergy.basal, ggStandEnergy.basal, ggPhase.basal, 
                   nrow = 3, ncol = 1, common.legend = TRUE, legend = "bottom")
gg.basal
#savePlot(gg.basal, "bodeplot_basal", w = 8, h = 9)
```


### Biologische Raten
```{r Abbildungen Biologische Raten, echo=FALSE, eval = TRUE,  message= FALSE}
dataModel <- read.table("modelAnalysis/result_bio.txt",header=T) %>% arrange(frequency) 
ggPhase.bio <- plotPhase(dataModel, dataModel$parameterset, colorScale2, fontSettings, "TF/Zielgen:", "Frequenz [AU]")
ggEnergy.bio <- plotEnergy(dataModel, dataModel$parameterset, colorScale2, fontSettings, "TF/Zielgen:", "Frequenz [AU]")
ggStandEnergy.bio <- plotStandEnergy(dataModel, dataModel$parameterset, colorScale2, fontSettings, "TF/Zielgen:", "Frequenz [AU]")

gg.bio <- ggarrange(ggEnergy.bio, ggStandEnergy.bio, ggPhase.bio, 
                   nrow = 3, ncol = 1, common.legend = TRUE, legend = "bottom")
gg.bio
savePlot(gg.bio, "bodeplot_bio", w = 8, h = 9)
```

## Zeitverlauf
```{r Zeitverlauf, echo = FALSE, eval = TRUE, message = FALSE}
dataTimeCourse <- read.table("modelAnalysis/Cpp_model_RelA_VCAM1_f_0.5.txt",header=T)

ggStart <- dataTimeCourse[1:100, c('t','k0', 'TF_mRNA', 'TF_protein', 'target_mRNA')] %>% melt(id.vars = 't', mesure.vars = c('k0', 'TF_mRNA', 'TF_protein', 'target_mRNA')) %>%
ggplot(aes(x=t, y=value, colour = variable)) +
  geom_path() +
  colorScale4 +
  fontSettings +
  ylab("Anzahl") +
  xlab("Zeit [h]") + 
  coord_cartesian(ylim=c(-1,4))

ggAll <- dataTimeCourse[1:2500, c('t','k0', 'TF_mRNA', 'TF_protein', 'target_mRNA')] %>% melt(id.vars = 't', mesure.vars = c('k0', 'TF_mRNA', 'TF_protein', 'target_mRNA')) %>%
ggplot(aes(x=t, y=value, colour = variable)) +
  geom_line() +
  colorScale4 +
  fontSettings +
  ylab("Anzahl") +
  xlab("Zeit [h]")

ggEqui <- dataTimeCourse[6000:6100, c('t','k0', 'TF_mRNA', 'TF_protein', 'target_mRNA')] %>% melt(id.vars = 't', mesure.vars = c('k0', 'TF_mRNA', 'TF_protein', 'target_mRNA')) %>%
ggplot(aes(x=t, y=value, colour = variable)) +
  geom_line() +
  colorScale4 +
  fontSettings +
  ylab("Anzahl") +
  xlab("Zeit [h]")

gg.time <- ggarrange(ggStart, ggAll, ggEqui, 
                   nrow = 3, ncol = 1, common.legend = TRUE, legend = "bottom")
gg.time
savePlot(gg.time, "timeCourse_RelA", w = 8, h = 9)

```